const waifus = [
  {
    name: 'Rem',
    anime: 'Re:Zero − Starting Life in Another World',
    description: "Rem est une femme de chambre au manoir de Roswaal. Discrète et dévouée, elle voue un amour inconditionnel à Subaru Natsuki et se révèle être une combattante redoutable au fléau.",
    image_url: 'https://cdn.myanimelist.net/images/characters/13/610829.jpg',
    hair_color: 'blue',
    personality: 'Dévouée, Courageuse, Loyale',
    rating: 9.8,
  },
  {
    name: 'Zero Two',
    anime: 'DARLING in the FranXX',
    description: "Zero Two est une hybride humain-klaxosaure et pilote d'élite. Connue pour sa personnalité enflammée et ses cornes rouges iconiques, elle cherche à devenir pleinement humaine.",
    image_url: 'https://cdn.myanimelist.net/images/characters/14/559013.jpg',
    hair_color: 'pink',
    personality: 'Audacieuse, Passionnée, Libre',
    rating: 9.7,
  },
  {
    name: 'Asuna Yuuki',
    anime: 'Sword Art Online',
    description: "Asuna est une escrimeuse hors pair surnommée « L'Éclair ». L'une des joueuses les plus puissantes de SAO, elle est la compagne de Kirito.",
    image_url: 'https://cdn.myanimelist.net/images/characters/15/262053.jpg',
    hair_color: 'orange',
    personality: 'Déterminée, Courageuse, Attentionnée',
    rating: 9.3,
  },
  {
    name: 'Mikasa Ackerman',
    anime: 'Attack on Titan',
    description: "Mikasa est considérée comme la soldate la plus forte de la 104e promotion. Protectrice farouche d'Eren, elle maîtrise le combat avec une maîtrise absolue.",
    image_url: 'https://cdn.myanimelist.net/images/characters/9/215563.jpg',
    hair_color: 'black',
    personality: 'Stoïque, Protectrice, Loyale',
    rating: 9.5,
  },
  {
    name: 'Nezuko Kamado',
    anime: 'Demon Slayer: Kimetsu no Yaiba',
    description: "Nezuko est la petite sœur de Tanjiro, transformée en démon. Elle conserve malgré tout sa compassion et lutte pour protéger les humains.",
    image_url: 'https://cdn.myanimelist.net/images/characters/2/378254.jpg',
    hair_color: 'black',
    personality: 'Douce, Brave, Protectrice',
    rating: 9.6,
  },
  {
    name: 'Emilia',
    anime: 'Re:Zero − Starting Life in Another World',
    description: "Emilia est une demi-elfe candidate au trône de Lugnica. Généreuse et sincère, elle ignore parfois les conventions sociales par naïveté.",
    image_url: 'https://cdn.myanimelist.net/images/characters/14/599667.jpg',
    hair_color: 'silver',
    personality: 'Naïve, Généreuse, Déterminée',
    rating: 9.0,
  },
  {
    name: 'Megumin',
    anime: "KonoSuba: God's Blessing on This Wonderful World!",
    description: "Megumin est une jeune archi-mage obsédée par la magie d'explosion. Elle ne connaît qu'un seul sort — mais il est dévastateur.",
    image_url: 'https://cdn.myanimelist.net/images/characters/14/349249.jpg',
    hair_color: 'brown',
    personality: 'Excentrique, Dramatique, Passionnée',
    rating: 9.4,
  },
  {
    name: 'Aqua',
    anime: "KonoSuba: God's Blessing on This Wonderful World!",
    description: "Aqua est une déesse envoyée dans un monde fantastique avec Kazuma. Malgré son statut divin, elle est souvent maladroite et comique.",
    image_url: 'https://cdn.myanimelist.net/images/characters/13/616878.jpg',
    hair_color: 'blue',
    personality: 'Joyeuse, Orgueilleuse, Naïve',
    rating: 8.9,
  },
  {
    name: 'Violet Evergarden',
    anime: 'Violet Evergarden',
    description: "Violet est une ancienne enfant-soldat devenue Auto Memory Doll. Elle rédige des lettres pour autrui tout en cherchant le sens des mots « je t'aime ».",
    image_url: 'https://cdn.myanimelist.net/images/characters/9/345616.jpg',
    hair_color: 'blonde',
    personality: 'Stoïque, Déterminée, En évolution',
    rating: 9.5,
  },
  {
    name: 'Chika Fujiwara',
    anime: 'Kaguya-sama: Love Is War',
    description: "Chika est la secrétaire du conseil étudiant. Son énergie débordante et son comportement imprévisible bouleversent constamment les plans de ses camarades.",
    image_url: 'https://cdn.myanimelist.net/images/characters/15/559031.jpg',
    hair_color: 'pink',
    personality: 'Énergique, Joyeuse, Imprévisible',
    rating: 9.2,
  },
  {
    name: 'Raphtalia',
    anime: 'The Rising of the Shield Hero',
    description: "Raphtalia est une demi-humaine tanuki et première compagne de Naofumi. Elle passe d'une esclave timide à une guerrière puissante et loyale.",
    image_url: 'https://cdn.myanimelist.net/images/characters/6/374252.jpg',
    hair_color: 'brown',
    personality: 'Loyale, Courageuse, Compatissante',
    rating: 9.1,
  },
  {
    name: 'Erza Scarlet',
    anime: 'Fairy Tail',
    description: "Erza est une mage S-Class de la guilde Fairy Tail, surnommée « Titania ». Elle peut changer d'armure et d'arme en combat grâce à sa magie de rééquipement.",
    image_url: 'https://cdn.myanimelist.net/images/characters/12/492254.jpg',
    hair_color: 'red',
    personality: 'Stricte, Juste, Attentionnée',
    rating: 9.3,
  },
  {
    name: 'Rias Gremory',
    anime: 'High School DxD',
    description: "Rias est une diablesse de haut rang et présidente du Club de Recherche Occulte. Elle est fière, protectrice envers ses servants et d'une beauté légendaire.",
    image_url: 'https://cdn.myanimelist.net/images/characters/5/150011.jpg',
    hair_color: 'red',
    personality: 'Fière, Attentionnée, Confiante',
    rating: 8.8,
  },
  {
    name: 'Tohru',
    anime: "Miss Kobayashi's Dragon Maid",
    description: "Tohru est un dragon puissant transformé en femme de chambre dévouée à Kobayashi. Elle possède des pouvoirs magiques extraordinaires et une affection sans bornes.",
    image_url: 'https://cdn.myanimelist.net/images/characters/9/535713.jpg',
    hair_color: 'blonde',
    personality: 'Enthousiaste, Dévouée, Puissante',
    rating: 9.0,
  },
  {
    name: 'Hinata Hyuga',
    anime: 'Naruto',
    description: "Hinata est une kunoichi du clan Hyuga qui admire Naruto. Elle surmonte sa timidité naturelle pour devenir une ninja hors pair qui se bat pour ceux qu'elle aime.",
    image_url: 'https://cdn.myanimelist.net/images/characters/6/278736.jpg',
    hair_color: 'black',
    personality: 'Timide, Déterminée, Bienveillante',
    rating: 9.1,
  },
  {
    name: 'Rukia Kuchiki',
    anime: 'Bleach',
    description: "Rukia est une Soul Reaper qui transfère ses pouvoirs à Ichigo Kurosaki. Malgré ses origines nobles, elle reste humble et profondément dévouée à son devoir.",
    image_url: 'https://cdn.myanimelist.net/images/characters/2/78215.jpg',
    hair_color: 'black',
    personality: 'Sérieuse, Loyale, Honorable',
    rating: 9.2,
  },
  {
    name: 'Nami',
    anime: 'One Piece',
    description: "Nami est la navigatrice de l'équipage du Chapeau de Paille. Dotée d'une intelligence cartographique exceptionnelle, elle manie le Clima-Tact avec dextérité.",
    image_url: 'https://cdn.myanimelist.net/images/characters/8/627117.jpg',
    hair_color: 'orange',
    personality: 'Astucieuse, Matérialiste, Attentionnée',
    rating: 8.9,
  },
  {
    name: 'Nico Robin',
    anime: 'One Piece',
    description: "Robin est l'archéologue de l'équipage du Chapeau de Paille. Seule personne capable de lire les Ponéglyphes, elle possède le Fruit Hana Hana.",
    image_url: 'https://cdn.myanimelist.net/images/characters/16/363700.jpg',
    hair_color: 'black',
    personality: 'Calme, Mystérieuse, Intelligente',
    rating: 9.4,
  },
  {
    name: 'Winry Rockbell',
    anime: 'Fullmetal Alchemist: Brotherhood',
    description: "Winry est une prodige en ingénierie mécanique qui entretient l'automail d'Edward Elric. Passionnée et têtue, elle est le soutien émotionnel des frères Elric.",
    image_url: 'https://cdn.myanimelist.net/images/characters/15/84336.jpg',
    hair_color: 'blonde',
    personality: 'Passionnée, Attentionnée, Têtue',
    rating: 9.0,
  },
  {
    name: 'Miku Nakano',
    anime: 'The Quintessential Quintuplets',
    description: "Miku est la troisième des quintuplées Nakano. Réservée et introvertie, elle cache une passion profonde pour l'histoire et développe des sentiments sincères pour Futaro.",
    image_url: 'https://cdn.myanimelist.net/images/characters/15/507743.jpg',
    hair_color: 'brown',
    personality: 'Réservée, Passionnée, Sincère',
    rating: 9.1,
  },
];

const seedWaifus = async (pool) => {
  const query = `
    INSERT INTO waifus (name, anime, description, image_url, hair_color, personality, rating)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
  `;
  for (const w of waifus) {
    await pool.query(query, [w.name, w.anime, w.description, w.image_url, w.hair_color, w.personality, w.rating]);
  }
};

module.exports = { seedWaifus };
